### ISSUE TITLE
is the quantification performance dependent on the number of identified components?

### ISSUE THREAD

**Issue by ZJiangsan** [XiaqiongFan/DeepRaman#1]
![001](https://github.com/user-attachments/assets/de51c001-5e62-4ab9-a120-c6b8ba909f83)
as shown in the file “[testing_Multi_component_mixture.py](https://github.com/XiaqiongFan/DeepRaman/blob/main/DeepRaman/testing_Multi_component_mixture.py)”

**Comment by zmzhang** [comment]
This step normalizes the estimated ratios, so that the sum of the ratios of all components in the mixture is guaranteed to be equal to 1.

**Comment by ZJiangsan** [comment]
Then all the components inside the mixture have to be correctly identified to guarantee an excellent quantification. This can be so difficult in real-world applications.

**Comment by zmzhang** [comment]
In DeepRaman, the compound ratios obtained using NN-EN is mainly used for further filtering of false positive components. It is only partially useful for estimating the relative content of compounds.

> Then all the components inside the mixture have to be correctly identified to guarantee an excellent quantification. This can be so difficult in real-world applications.
